# Generated by Django 6.0 on 2025-12-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'pendente'), ('CONCLUIDA', 'concluida')], default='PENDENTE', max_length=10)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
